In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

In [6]:
iris=datasets.load_iris()
print(iris.DESCR)
print(iris.feature_names)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [109]:
#print(iris['data'])#Prints all the feature values
X=iris['data'][:,[2,3]]#Extracting petal length and petal width only
y=iris['target']#Target class values
x_l0=X[0:50]#first 50 feature values corresponding to class 1(label 0)
x_l1=X[50:100]#next 50 feature values corresponding to class 2(label 1)
x_l2=X[100:]#next 50 feature values corresponding to class 3(label 2)
#print(x_l0)
#print(x_l1)
#print(x_l2)
y_l0=y[0:50]#class 1 values (label 0)
y_l1=y[50:100]#class 2 values (label 1)
y_l2=y[100:]#class 3 values (label 2)
#print(y_l0)
#print(y_l1)
#print(y_l2)

In [157]:
x0=np.array(x_l0[0:40])
x1=np.array(x_l1[0:40])
x2=np.array(x_l2[0:40])
y0=np.array(y_l0[0:40])
y1=np.array(y_l1[0:40])
y_dummy2=np.array([1 for i in range(40)]).reshape(40,1)#only 2 classes are there(label 0 and label 1). creating a dummy array with label 1
#y2=np.array(y_l2[0:40]) #Required for multiclass classification
X=np.concatenate([x0,x1,x2],axis=0)#concatenating training feature values
print(X)
print(len(X))

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [6.  2.5]
 [5.1 1.9]
 [5.9 2.1]
 [5.6 1.8]
 [5.8 2.2]
 [6.6 2.1]
 [4.5 1.7]
 [6.3 1.8]
 [5.8 1.8]
 [6.1 2.5]
 [5.1 2. ]

In [162]:
y=np.concatenate([y0,y1,y_dummy2],axis=None)#concatenating training output class values
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [171]:
xtest_0=np.array(x_l0[40:50])#last 10 feature values corresponding to class 1(label 0)
xtest_1=np.array(x_l1[40:50])#last 10 feature values corresponding to class 2(label 1)
xtest_2=np.array(x_l2[40:50])#last 10 feature values corresponding to class 3(label 2)
ytest_0=np.array(y_l0[40:50])#class 1 values (label 0)
ytest_1=np.array(y_l1[40:50])#class 2 values (label 1)
y_test_dummy=np.array([1 for i in range(10)]).reshape(10,1)#only 2 classes are there(label 0 and label 1). creating a dummy array with label 1
#y2=np.array(y_l2[0:40]) #Required for multiclass classification
X_test=np.concatenate([xtest_0,xtest_1,xtest_2],axis=0)
y_test=np.concatenate([ytest_0,ytest_1,y_test_dummy],axis=None)
print(X_test)
print(len(X))
print(y_test)

[[1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.4 1.2]
 [4.6 1.4]
 [4.  1.2]
 [3.3 1. ]
 [4.2 1.3]
 [4.2 1.2]
 [4.2 1.3]
 [4.3 1.3]
 [3.  1.1]
 [4.1 1.3]
 [5.6 2.4]
 [5.1 2.3]
 [5.1 1.9]
 [5.9 2.3]
 [5.7 2.5]
 [5.2 2.3]
 [5.  1.9]
 [5.2 2. ]
 [5.4 2.3]
 [5.1 1.8]]
120
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [164]:
model=LogisticRegression()
model.fit(X,y)
y_predict=model.predict(X_test)
print(y_predict)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


/home/asapadmin/miniconda3/envs/asap/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [165]:
print(model.score(X_test,y_test))

1.0


# Softmax Regression for mutliclass classification

In [168]:
y2=np.array(y_l2[0:40])#class 3 training output values(label 2)
ytest_2=np.array(y_l2[40:50])#class 3 testing output values(label 2)
y_multi_train=np.concatenate([y0,y1,y2],axis=0)
y_multi_test=np.concatenate([ytest_0,ytest_1,ytest_2],axis=0)
print(y_multi_train)
print(y_multi_test)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [169]:
model=LogisticRegression(multi_class='multinomial',solver='lbfgs')
model.fit(X,y_multi_train)
y_multi_predit=model.predict(X_test)
print(y_multi_predit)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [170]:
print(model.score(X_test,y_multi_test))

1.0
