In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x1=np.array([6,8,10,14,18]).reshape(5,1)
x2=np.array([2,1,0,2,0]).reshape(5,1)
y=np.array([7,9,13,17.5,18]).reshape(5,1)
c1=np.array([1 for i in range(5)]).reshape(5,1)
X=np.concatenate([c1,x1,x2],axis=1)
print(X)


[[ 1  6  2]
 [ 1  8  1]
 [ 1 10  0]
 [ 1 14  2]
 [ 1 18  0]]


In [3]:
from numpy.linalg import lstsq
THETA_LS=lstsq(X,y)[0]
print(THETA_LS)

[[1.1875    ]
 [1.01041667]
 [0.39583333]]


/home/asapadmin/miniconda3/envs/asap/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [4]:
xx1=np.array([8,9,11,16,12]).reshape(5,1)
xx2=np.array([2,0,2,2,0]).reshape(5,1)
y_test=np.array([11,8.5,15,18,11]).reshape(5,1)
X_test=np.concatenate([c1,xx1,xx2],axis=1)
print(X_test)



[[ 1  8  2]
 [ 1  9  0]
 [ 1 11  2]
 [ 1 16  2]
 [ 1 12  0]]


In [5]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()


In [6]:
model.fit(X,y)
y_predict=model.predict(X_test)
print(y_predict)

[[10.0625    ]
 [10.28125   ]
 [13.09375   ]
 [18.14583333]
 [13.3125    ]]


In [7]:
print(model.score(X_test,y_test))

0.7701677731318466
