In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# #Training data

In [ ]:
X_train=np.array([6,8,10,14,18]).reshape(5,1)#Transforming the training independent data into 1-D vector
y_train=np.array([7,9,13,17.5,18]).reshape(5,1)#Transforming the training dependent data into 1-D vector

# #Testing data

In [15]:
X_test=np.array([9,6,8,11,16]).reshape(5,1)#Transforming the testing independent data into 1-D vector
y_test=np.array([11,8,12,15,18]).reshape(5,1)#Transforming the testing dependent data into 1-D vector

In [16]:
model=LinearRegression()
model.fit(X_train,y_train)#Fitting the y_train values versus X_train values

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
model.score(X_test,y_test)#Finding the R2 score

0.8217876720396842

In [18]:
from sklearn.preprocessing import PolynomialFeatures
polyFeatures=PolynomialFeatures(degree=2)#Creating object of the class PolynomialFeatures, passing argument 2 as degree

X_train_quadratic=polyFeatures.fit_transform(X_train)#Transforming the linear train data into quadratic
X_test_quadratic=polyFeatures.fit_transform(X_test)#Transforming the linear test data into quadratic
print(X_train_quadratic)

[[  1.   6.  36.]
 [  1.   8.  64.]
 [  1.  10. 100.]
 [  1.  14. 196.]
 [  1.  18. 324.]]


In [19]:
modelQuadratic=LinearRegression()#Creating the object
modelQuadratic.fit(X_train_quadratic,y_train)#Fitting the model
modelQuadratic.score(X_test_quadratic,y_test)#Finding the R2 score

0.8712597219409937